### ISSUE TITLE
How to load a fbx file and show in a widget?

### ISSUE THREAD

**Issue by klaszlo8207** [brendan-duncan/dart_fbx#1]
Is there any example for mobile?

**Comment by klaszlo8207** [comment]
I saw this is only for WebGL, so just web, not for mobile. Also I created a dart View that can load and show the parsed FBX animated file via CustomPainter. 

Still have some probleme (texturing via canvas) but it is working

**Comment by brendan-duncan** [comment]
The library isn't really specific to WebGL or any other platform, though I did write a WebGL example, https://github.com/brendan-duncan/dart_fbx/tree/master/web. The library just parses FBX files as best as it can (there is no public spec, so it's all just reverse engineered without any guarantee of accuracy or compliance) and generates the geometry data necessary to render with WebGL, OpenGL, Metal, etc. But it doesn't define the code necessary to render the resulting geometry. I'm guessing you're using Flutter, which I don't know much about, but I assume it has some sort of OpenGL/Metal view widget. You'd have to write your own GL/Metal/etc rendering code for that. I'm curious how Flutter deals with cross-platform 3D rendering since iOS only likes Metal and not GL...I'll have to look that up.
