### ISSUE TITLE
FbxDisplayMesh vertices maybe indices?

### ISSUE THREAD

**Issue by klaszlo8207** [brendan-duncan/dart_fbx#2]
that vertices variant is indices not?  This is so confusing

**Comment by klaszlo8207** [comment]
Uint16List vertices; -> Uint16List indices !!!

**Comment by brendan-duncan** [comment]
Different graphics libraries call it differently, either vertex list or index list. Both are correct, I just picked one, probably was using another library that called them vertices at the time I wrote it. I can add an alias called indices if it will make it less confusing for you.

**Comment by klaszlo8207** [comment]
Yeah it is index, index of the face or the point. Vertices just
Point3d/Vector3 s, also index is just an int, vertex is float/double

https://www.mathsisfun.com/geometry/vertices-faces-edges.html

Brendan Duncan <notifications@github.com> ezt írta (időpont: 2020. jan. 9.,
Cs 19:54):

**Comment by brendan-duncan** [comment]
Like I said, the nomenclature has changed over the years. Vertices differ from points, depending on how the geometry library is defined. Two vertices may point to the same point but different normals and texture coordinates, for example. The name "indices" evolved from "vertices", as a generic form.

In this libraries case, going with the more generic indices is appropriate and I'll get that checked in shortly. I'm just doing some dartanalysis cleanup first, since I haven't touched this library in quite a while.

**Comment by brendan-duncan** [comment]
The change has been committed and published as a new version, 0.2.0.

**Comment by klaszlo8207** [comment]
Thanks
